### ISSUE TITLE
Premium LIBRARY - Offline app

### ISSUE THREAD

**Issue by Humberto-MH** [siwalikm/coffitivity-offline#10]
Hi.
Got Premium, but I can see the premium LIBRARY list in the Offline app. Am I doing something wrong? 
Thanks,

**Comment by siwalikm** [comment]
Hi @Humberto-MH, right now this app supports **only** the free tracks. This is primarily because, being an offline app the paid tracks would be also part of the downloaded app's source code which is a real concern. But we have plans to look into this soon. Closing this issue as it's a feature already in the pipeline. cheers
