### ISSUE TITLE
Re-create menu bar ui?

### ISSUE THREAD

**Issue by devinrhode2** [siwalikm/coffitivity-offline#12]
I miss the classic Coffitivity living in the menu bar... any chance the company/official project would share the code for that with you???

**Comment by devinrhode2** [comment]
I tried downloading the classic Coffitivity from the mac app store but it's no longer available in the U.S. (I guess I could try signing up for a vpn, but I don't even know which countries can download it)

**Comment by siwalikm** [comment]
Hi! @devinrhode2, I have considered the menu app initially but halted the idea because menu-bar apps only work on mac, so later on we won't be able to build the same electron app for windows and linux versions as the app won't work on other OSs where as this will.

Btw. in fact I myself am a huge fan of menu-bar apps. 😍
